spring.application.name=IPL-TEAM

#config server port
server.port=9091

#optional
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true

#randam instance
eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

spring.config.import=optional:configserver:http://localhost:9999


#Admin config
spring.boot.admin.client.url=http://localhost:8888
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always






