spring.application.name=IPL-Api-Gateway-Server

#api gateway server port
server.port=8899

management.endpoints.web.exposure.include=*

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true

spring.boot.admin.client.url=http://localhost:8888


# Route 1
spring.cloud.gateway.routes[0].id=IPL-Player
spring.cloud.gateway.routes[0].uri=http://localhost:9090
spring.cloud.gateway.routes[0].predicates[0]=Path=/player/**

# Route 2
spring.cloud.gateway.routes[1].id=IPL-Team-Service
spring.cloud.gateway.routes[1].uri=http://localhost:9091
spring.cloud.gateway.routes[1].predicates[0]=Path=/team/**