spring.application.name=IPL_Api_Gateway_Server

#api gateway server port
server.port=8899

management.endpoints.web.exposure.include=*

spring.boot.admin.client.url=http://localhost:8888


# Route 1
spring.cloud.gateway.routes[0].id=IPL_Player
spring.cloud.gateway.routes[0].uri=http://localhost:9090
spring.cloud.gateway.routes[0].predicates[0]=Path=/player/**

# Route 2
spring.cloud.gateway.routes[1].id=IPL_Team_Service
spring.cloud.gateway.routes[1].uri=http://localhost:9091
spring.cloud.gateway.routes[1].predicates[0]=Path=/team/**