spring.application.name=IPL_Eureka_Server

#eureka server port
server.port=8761

#Disable to register itself
eureka.client.register-with-eureka=false

#Disable to fetch registry
eureka.client.fetch-registry=false

