spring.application.name=IPL_Player

#Ipl player server port
server.port=9090

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

spring.config.import=optional:configserver:http://localhost:9999

management.endpoints.web.exposure.include=*

spring.boot.admin.client.url=http://localhost:8888/


