spring.application.name=IPL-PLAYER

#Ipl player server port
server.port=9090

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=true

eureka.instance.instance-id=${spring.application.name}:${server.port}:${random.value}

#Center
spring.config.import=optional:configserver:http://localhost:9999

#Admin server config
spring.boot.admin.client.url=http://localhost:8888
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Circuit Breaker Instance
resilience4j.circuitbreaker.instances.IPL-TEAM.failure-rate-threshold=50

# Minimum number of calls before calculating failure rate
resilience4j.circuitbreaker.instances.IPL-TEAM.minimum-number-of-calls=5

# Number of calls stored in sliding window
resilience4j.circuitbreaker.instances.IPL-TEAM.sliding-window-size=10

# Type of sliding window (COUNT_BASED or TIME_BASED)
resilience4j.circuitbreaker.instances.IPL-TEAM.sliding-window-type=COUNT_BASED

# Time circuit remains OPEN before moving to HALF_OPEN
resilience4j.circuitbreaker.instances.IPL-TEAM.wait-duration-in-open-state=10s

# Calls allowed in HALF_OPEN state
resilience4j.circuitbreaker.instances.IPL-TEAM.permitted-number-of-calls-in-half-open-state=3

# Automatically move from OPEN to HALF_OPEN
resilience4j.circuitbreaker.instances.IPL-TEAM.automatic-transition-from-open-to-half-open-enabled=true

# Slow call threshold (milliseconds)
resilience4j.circuitbreaker.instances.IPL-TEAM.slow-call-duration-threshold=2s

# Slow call rate threshold
resilience4j.circuitbreaker.instances.IPL-TEAM.slow-call-rate-threshold=50

# Record exceptions as failures
resilience4j.circuitbreaker.instances.IPL-TEAM.record-exceptions=java.lang.Exception

# Ignore specific exceptions
resilience4j.circuitbreaker.instances.IPL-TEAM.ignore-exceptions=java.lang.IllegalArgumentException






